version: '3.9'

services:
  app:
    container_name: mas-app
    build:
      context: .
      dockerfile: '.docker/Dockerfile'
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      MONGO_URI: ${MONGO_URI}
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:7.0
    container_name: mas-mongo
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INIT_USERNAME=${MONGO_INIT_USERNAME}
      - MONGO_INIT_PASSWORD=${MONGO_INIT_PASSWORD}
      - MONGO_INIT_DB=${MONGO_INIT_DB}
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
